//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuncCalc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res_mathjax {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_mathjax() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuncCalc.Res-mathjax", typeof(Res_mathjax).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   置換積分法を利用 {0}をtと置く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _DisplacementIntegralWay1 {
            get {
                return ResourceManager.GetString("_DisplacementIntegralWay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \int {{0}} dt = {1} なので に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _DisplacementIntegralWay2 {
            get {
                return ResourceManager.GetString("_DisplacementIntegralWay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \int {{0} dt} = \int {\frac { 1 } {1} {2} d{4} } = {3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _DisplacementIntegralWay3 {
            get {
                return ResourceManager.GetString("_DisplacementIntegralWay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} = -(b/a) = {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _LinerEquationWay1 {
            get {
                return ResourceManager.GetString("_LinerEquationWay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分積分法を使用 {6} \int ({0})d{1} = {6} ((({2}) \int {({3}) d{1}}) - \int {({4} {5}) d{1}}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _PartialIntegralWay1 {
            get {
                return ResourceManager.GetString("_PartialIntegralWay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}_1 = \frac {-b+\sqrt {b^2-4a*c} } {2a} = {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _QuadraticEquationWay1 {
            get {
                return ResourceManager.GetString("_QuadraticEquationWay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}_2 = \frac {-b-\sqrt {b^2-4a*c} } {2a} = {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string _QuadraticEquationWay2 {
            get {
                return ResourceManager.GetString("_QuadraticEquationWay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一次方程式として計算: ax + b = 0 → a={0}, b={1}なので に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsLinerEquation {
            get {
                return ResourceManager.GetString("AsLinerEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二次方程式として計算: ax^2 + bx + c = 0 → a={0}, b={1}, c={2}なので に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsQuadraticEquation {
            get {
                return ResourceManager.GetString("AsQuadraticEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} = {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は積分定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntegralConstant {
            get {
                return ResourceManager.GetString("IntegralConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}が独立した関係にある場合のみ成り立つ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnrelationWith {
            get {
                return ResourceManager.GetString("UnrelationWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   = {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Way {
            get {
                return ResourceManager.GetString("Way", resourceCulture);
            }
        }
    }
}
